// <auto-generated />
namespace proiect_ProgramareAvansataPePlatforma.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Orders3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Orders3));
        
        string IMigrationMetadata.Id
        {
            get { return "202411290423221_Orders3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
